[package]
name = "scripter"
version = "0.10.7"
edition = "2021"

[dependencies]
chrono = { version = "0.4.26", features = [] }
crossbeam-channel = "0.5.8"
iced = { version = "0.9.0", features = ["debug", "smol", "image", "glow"] }
iced_lazy = "0.6.1"
rand = { version = "0.8.5", features = ["std"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
once_cell = "1.18.0"
