[package]
name = "scripter"
version = "0.14.2"
edition = "2021"

[dependencies]
chrono = { version = "0.4.35", features = [] }
crossbeam-channel = "0.5.12"
iced = { version = "0.9.0", features = ["debug", "smol", "image", "glow"] }
iced_lazy = "0.6.1"
rand = { version = "0.8.5", features = ["std"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
once_cell = "1.19.0"
open = "5.1.2"
bitflags = { version = "2.5.0", features = ["serde"] }
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
