[package]
name = "scripter"
version = "0.2.0"
edition = "2021"

[dependencies]
iced = { version = "0.9.0", features = ["debug", "smol"] }
iced_lazy = "0.6.1"
iced_native = "0.10.3"
once_cell = "1.16.0"
rev_buf_reader = "0.3.0"
