[package]
name = "scripter"
version = "0.14.5"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
crossbeam-channel = { version = "0.5.12", default-features = false, features = ["std"] }
iced = { version = "0.12.1", default-features = false, features = ["debug", "smol", "advanced", "lazy", "image", "wgpu", "fira-sans"] }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.116", default-features = false, features = ["std"] }
once_cell = { version = "1.19.0", default-features = false }
open = { version = "5.1.2", default-features = false }
bitflags = { version = "2.5.0", default-features = false, features = ["serde"] }
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
smol_str = { version = "0.2.1", default-features = false }
