[package]
name = "scripter"
version = "0.4.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.8"
iced = { version = "0.9.0", features = ["debug", "smol", "image"] }
iced_lazy = "0.6.1"
iced_native = "0.10.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
