name: Builds and Tests

on:
  push:
    branches: '*'
    paths-ignore:
    - README.md
    - LICENSE
    - CONTRIBUTING.md
    - .gitignore
    - '.github/**'
    - '!.github/workflows/rust.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose

    - name: Move the executable to data folder
      run: mv target/release/scripter data/linux/scripter
    - name: Copy common data to data folder
      run: cp -r data/common/* data/linux/
    - name: Upload linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux (Ubuntu)
        path: data/linux/*

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release --verbose

    - name: Add windows icon
      run: cargo rustc --release -- -C link-args="res/resources.res"
    - name: Move the executable to data folder
      run: mv target/release/scripter.exe data/windows/scripter.exe
    - name: Copy common data to data folder
      run: cp -r data/common/* data/windows/
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: data/windows/*
